# Generated by Django 4.1.6 on 2023-03-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "created_by",
                    models.CharField(
                        default=None, max_length=50, null=True, verbose_name="생성한 사람"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
                (
                    "updated_by",
                    models.CharField(
                        default=None, max_length=50, null=True, verbose_name="수정한 사람"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
