version: "3.9"
services:

  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    volumes:
      - ..:/src
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend